version: '3.8'
services:
  backend:
    build: .
    ports:
      - '${PORT}:8080'
    volumes:
      - ${BOX_PATH}:/app/box
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./backend.env
  mydb:
    image: 'mysql'
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - ./mysql.env

volumes:
  mysql-volume:
