version: '3.8'
services:
  mkcloud-backend:
    build: .
    ports:
      - '${PORT}:8080'
    volumes:
      - ${BOX_PATH}:/app/box
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./backend.env
    depends_on:
      - mkcloud-db
  mkcloud-db:
    image: 'mysql'
    volumes:
      - mkcloud-mysql-volume:/var/lib/mysql
    env_file:
      - ./mysql.env

volumes:
  mkcloud-mysql-volume:
